services:
  ray-head:
    image: nvcr.io/nvidia/pytorch:25.03-py3
    container_name: ray-head
    runtime: nvidia
    ports:
      - "8265:8265"  # Ray dashboard
      - "6379:6379"  # Redis port
      - "10001:10001"  # Ray object manager
      - "8080:8080"   # Web visualization (if any)
    environment:
      - NVIDIA_VISIBLE_DEVICES=0,1  # Use 2 GPUs for the head node
      - RAY_HEAD_IP=ray-head
    volumes:
      - ../../..:/workspace/verl  # Mount the verl repository
      - /path/to/data:/workspace/data  # Data path
      - /path/to/checkpoints:/workspace/checkpoints  # Checkpoint path
    shm_size: 1g
    ulimits:
      memlock: -1
      stack: 67108864
    command: >
      bash -c "cd /workspace/verl && 
               pip install --no-cache-dir -e . &&
               pip install ray[default]==2.9.3 &&
               pip install nvtx wandb transformers accelerate &&
               ray start --head --port=6379 --dashboard-host=0.0.0.0 --num-gpus=2 &&
               sleep infinity"
    networks:
      - ray_network

  # Container for running megatron SFT example
  megatron-sft:
    image: nvcr.io/nvidia/pytorch:25.03-py3
    container_name: megatron-sft
    runtime: nvidia
    depends_on:
      - ray-head
    environment:
      - NVIDIA_VISIBLE_DEVICES=0,1  # Use 2 GPUs
    volumes:
      - ../../..:/workspace/verl  # Mount the verl repository
      - /path/to/data:/workspace/data  # Data path
      - /path/to/checkpoints:/workspace/checkpoints  # Checkpoint path
    shm_size: 1g
    ulimits:
      memlock: -1
      stack: 67108864
    command: >
      bash -c "cd /workspace/verl && 
               pip install --no-cache-dir -e . &&
               pip install ray[default]==2.9.3 &&
               pip install nvtx wandb transformers accelerate &&
               pip install megatron-core &&
               # Clone and install Megatron-LM
               git clone https://github.com/NVIDIA/Megatron-LM.git /workspace/Megatron-LM &&
               cd /workspace/Megatron-LM &&
               pip install -e . &&
               cd /workspace/verl &&
               # Sleep to allow Ray to initialize fully
               sleep 10 &&
               # Run the Megatron example script
               bash examples/sft/megatron/run_llama2_7b_megatron.sh 2 /workspace/checkpoints/llama2-7b-megatron-sft"
    networks:
      - ray_network

networks:
  ray_network:
    driver: bridge 